version: '3'

services:

  slp_workspace:
    restart: always
    build:
      context: ./workspace
      args:
        - PUID=1000
        - PGID=1000
        - TZ=UTC
    volumes:
      - ../:/var/www
    env_file: env.dev
    tty: true

  slp_php-fpm:
    restart: always
    build: ./php-fpm
    volumes:
      - ../:/var/www
    expose:
      - "9000"
    links:
      - slp_workspace
    env_file: env.dev
    extra_hosts:
      - "dockerhost:172.17.0.1"

  slp_nginx:
    restart: always
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM=slp_php-fpm
    volumes:
      - ../:/var/www
      - ./logs/nginx/:/var/log/nginx
      - ./nginx/sites/:/etc/nginx/sites-available
    ports:
      - "80:80"
      - "443:443"
    links:
      - slp_php-fpm

  slp_db:
    restart: always
    image: postgres:9.6
    volumes:
      - slp_data:/var/lib/postgresql
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    env_file: env.dev

  slp_redis:
    restart: always
    image: redis:3.2
    ports:
      - "6379:6379"
    env_file: env.dev

volumes:
  slp_data:
